[package]
name = "hello_world"
version = "0.0.1"

edition = "2021"
[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
reqwest = { version = "*", features = ["blocking", "json"] }
azul = { git = "https://github.com/maps4print/azul" }